### ISSUE TITLE
hexo d 完之后，文件没有传到cos上

### ISSUE THREAD

**Issue by xiahaoyun** [sdlzhd/hexo-deployer-cos#1]
$ hexo d
INFO  Deploying: cos
INFO  Deploy done: cos

虽然已经出现了信息，但是cos仍旧是空空如也。

经过了尝试，并不是appId之类的有问题，因为发现要是这些有问题会报错。

cos相关配置：
![image](https://user-images.githubusercontent.com/16172717/30772123-ee6ba8c8-a087-11e7-8905-60a083389d9d.png)

![image](https://user-images.githubusercontent.com/16172717/30772130-0285a764-a088-11e7-9258-92a69efd7af9.png)

**Comment by xiahaoyun** [comment]
在腾讯云控制台里面也没有看到“写请求”

**Comment by sdlzhd** [comment]
等我一下，我今天稍晚点查看这个问题

**Comment by sdlzhd** [comment]
我已经确认了这个问题的存在（仅限新区域的cos），是腾讯更新了api的接口，正在看新的接口文档。
等我搞定了，给你反馈。

**Comment by sdlzhd** [comment]
bug已经修复。
不好意思，国庆假期回家，没能及时修复

**Comment by xiahaoyun** [comment]
十分感谢！！！
