### ISSUE TITLE
Can you give more detailed installation guide?

### ISSUE THREAD

**Issue by SuperFireFoxy** [sdlzhd/hexo-deployer-cos#2]
Can you give more detailed installation guide? cause I still feel a little confused about how to insert my local img into markdown file and upload these img when i deploy the blog.

**Comment by sdlzhd** [comment]
Maybe this is what you need
![note](https://user-images.githubusercontent.com/13533036/35189939-d39d9a08-fe90-11e7-8d78-099804c4d74e.jpg)
