### ISSUE TITLE
希望可以增加排除列表

### ISSUE THREAD

**Issue by sdlyfjx** [sdlzhd/hexo-deployer-cos#4]
蟹蟹你的开源项目！在使用中遇到如下问题希望可以实现：
当前的项目会删除COS上所有用户自建但本地没有的文件夹。希望可以在配置中加入忽略列表，在忽略列表中的文件或文件夹不会进行修改。
另外一个就是希望可以配置deploy的路径。当前是把所有内容deploy到bucket的根目录下了。如果在配置中可以指定deploy的路径就更好了。

**Comment by sdlyfjx** [comment]
问题2想到了：可以通过hexo中设置生成目录的方式解决。有一个新问题就是疼讯晕官方的SDK更新了。会有一个关于APPID的warning。

**Comment by sdlyfjx** [comment]
如果bucket不是空的，则无法deploy上去

**Comment by sdlzhd** [comment]
我会在近期更新这个项目，当时写得时候，SDK版本确实有点老。。。

你提到的几个问题：
1. 文件上传的逻辑需要重新梳理一下，基本还是会以本地为准，但是不应该删除bucket中已经有的文件
2. deploy的上传路径需要指定么，这是一个值得考虑的问题，并不难实现
3. bucket不为空无法deploy的问题，会和1一起解决

**Comment by sdlyfjx** [comment]
好的辛苦了。bucket已经有的文件而本地没有的文件不做删除这个功能我想最好是可以在配置中自定义。因为有的目录下是需要删除的，有的目录下不需要删除。所以有个忽略的配置是最好啦。

关于deploy指定上传路径问题，我在使用过程中遇到了类似需求，就是hexo的根目录实际上需要在cos的某个目录下，但是生成项目还是以public为根目录，部署上去后还是以cos为根目录。不过因为刚接触hexo，了解不够，可能有其他解决方案，或者这样做会带来其他问题。仅供您参考。



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： Dongdong <notifications@github.com>
日期: 2019/1/16 11:02 (GMT+08:00)
收件人： sdlzhd/hexo-deployer-cos <hexo-deployer-cos@noreply.github.com>
抄送： 址胱 <sdlyfjx@live.com>, Author <author@noreply.github.com>
主题： Re: [sdlzhd/hexo-deployer-cos] 希望可以增加排除列表 (#4)

我会在近期更新这个项目，当时写得时候，SDK版本确实有点老。。。

你提到的几个问题：

  1.  文件上传的逻辑需要重新梳理一下，基本还是会以本地为准，但是不应该删除bucket中已经有的文件
  2.  deploy的上传路径需要指定么，这是一个值得考虑的问题，并不难实现
  3.  bucket不为空无法deploy的问题，会和1一起解决

―

**Comment by sdlzhd** [comment]
简化了上传的逻辑，现在不会删除远程的文件
