### ISSUE TITLE
一个作为图床的提议

### ISSUE THREAD

**Issue by seainm** [sdlzhd/hexo-deployer-cos#5]
很多时候只是利用cos作为图床, 而不是把博客部署到cos上面; 
七牛云有一个图片自动上传的功能, 请问作者有没有写一个类似插件的想法呢

**Comment by sdlzhd** [comment]
你指的是这个项目么
https://gitee.com/k1988/hexo-qiniu-sync/

**Comment by seainm** [comment]
嗯， 是的！

**Comment by sdlzhd** [comment]
这个项目看起来不错，重复造个轮子，换成COS的，不过短期内我可能都没有时间开启一个新的项目
