### ISSUE TITLE
希望增加对全局环境变量的支持

### ISSUE THREAD

**Issue by 0x04c11db7** [sdlzhd/hexo-deployer-cos#6]
为在travis中使用，将_config.yml中得secretKey和secretId设置为环境变量，不能正确读取。
![图片](https://user-images.githubusercontent.com/25258169/59747899-87176b80-92ac-11e9-9cf0-2956ffcf0b1d.png)

![图片](https://user-images.githubusercontent.com/25258169/59747740-1a03d600-92ac-11e9-8189-1f44047830fa.png)

**Comment by sdlzhd** [comment]
我能看一下你现在通过命令行传参的方式么

hexo d

后面如何追加参数

**Comment by 0x04c11db7** [comment]
没有在hexo d后增加参数
在travis-CI中设置SecretKey和SecretId为环境变量。
![图片](https://user-images.githubusercontent.com/25258169/59825139-c0f87880-9365-11e9-881d-641722a2b67e.png)
travis在运行时将自动设置环境变量，并执行部署。
![图片](https://user-images.githubusercontent.com/25258169/59825239-103ea900-9366-11e9-9a95-0b48239035c0.png)
![图片](https://user-images.githubusercontent.com/25258169/59825260-23517900-9366-11e9-80ee-83fc71be9366.png)
而这个插件无法将配置文件中得${SecretKey}识别为全局变量。
![图片](https://user-images.githubusercontent.com/25258169/59825297-395f3980-9366-11e9-9ddb-e9e73ef8110a.png)
虽然可以在travis.yml中使用sed命令在hexo d前将${secretKey}替换成Key，但希望本插件能够考虑增加读取全局变量的判断。
这是我的配置文件。
[config.yml](https://github.com/myloft/blog/blob/master/_config.yml)
[.travis.yml](https://github.com/myloft/blog/blob/master/.travis.yml)

**Comment by sdlzhd** [comment]
额。。。我没有找到合适的方式在`hexo deploy`命令后追加参数，如果你有任何的资料，能不能提供下

**Comment by trim21** [comment]
不是通过`hexo deploy`传参，是从环境变量中读取

大概这样

```diff
diff --git a/lib/deployer.js b/lib/deployer.js
index a2ce95d..2f76aa3 100644
--- a/lib/deployer.js
+++ b/lib/deployer.js
@@ -20,8 +20,8 @@ module.exports = function (args) {
 
   // Create COS object
   let cos = new COS({
-    SecretId: args.secretId,
-    SecretKey: args.secretKey
+    SecretId: process.env.COS_SECRET_ID || args.secretId,
+    SecretKey: process.env.COS_SECRET_KEY || args.secretKey
   })
 
   // Bucket's configuration
@@ -52,8 +52,8 @@ module.exports = function (args) {
  * @return {boolean}
  */
 function checkHexoConfig (args) {
-  if (!args.secretId ||
-    !args.secretKey ||
+  if (!(process.env.COS_SECRET_ID || args.secretId) ||
+    !(process.env.COS_SECRET_KEY || args.secretKey) ||
     !args.bucket ||
     !args.region) {
     let tips = [

```

**Comment by trim21** [comment]
yaml展开环境变量似乎只是某些程序作为配置文件的feature，而不是yaml解析器的默认行为

**Comment by sdlzhd** [comment]
感谢你的提醒！我晚点将会更新代码，引进该功能！

**Comment by trim21** [comment]
十分感谢

**Comment by trim21** [comment]
同时希望bucket和region也能从环境变量中读取😀

**Comment by sdlzhd** [comment]
@Trim21 @myloft 

已经添加相应的环境变量读取，可以通过如下配置：

```
COS_SECRET_ID=yourSecretId
COS_SECRET_KEY=yourSecretKey
COS_BUCKET=yourBucket
COS_REGION=yourRegion
```

支持部分配置通过环境变量，当然，部署方式`type: cos`仍然是必须的。

感谢 @Trim21 提供的思路（被自己绕进去了，φ(≧ω≦*)♪）
