### ISSUE TITLE
作者啥时候增加一下增量更新机制，即只提交有更新的文件。

### ISSUE THREAD

**Issue by lxl80** [sdlzhd/hexo-deployer-cos#7]
试了一下，可以用。不过有个问题，每次部署都是全量覆盖上传，作者啥时候增加以下增量更新机制，即只提交有更新的文件？

**Comment by sdlzhd** [comment]
之前实现过一版，通过COS附带的ETag和本地文件的哈希做比对，如果不一致就上传，后来因为什么原因来着，去掉了。

我还是想实现这一个功能的，感觉很有必要，但是Hexo的部署阶段，没办法直接获取到更新的文件有哪些（我记得好像是这样），所以如果增加的话，也是从本地计算文件哈希，然后和服务器上的比对。文件数量多了以后，用运算成本换网络IO成本。

当然，可以提供一个配置项，让使用者决定是否启用该功能

**Comment by lxl80** [comment]
谢谢反馈

**Comment by sdlzhd** [comment]
不过似乎可以考虑给用户更多的个性化配置项，来决定如何deploy。

我重新考虑想想这个功能吧
