### ISSUE TITLE
使用hexo d -g，文件上传过程中卡死

### ISSUE THREAD

**Issue by fi6** [sdlzhd/hexo-deployer-cos#9]
console输出：

:\PTS\toutendo-blog> npm install hexo-deployer-cos --save
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\hexo-deployer-cos\node_modules\chokidar\node_modules\fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ hexo-deployer-cos@1.2.0
added 199 packages from 205 contributors and audited 389 packages in 11.105s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS F:\PTS\toutendo-blog> hexo clean
INFO  Validating config
INFO  Deleted database.
INFO  Deleted public folder.
PS F:\PTS\toutendo-blog> hexo d -g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 250 ms
INFO  Generated: categories/index.html
INFO  Generated: tags/index.html
INFO  Generated: archives/index.html
INFO  Generated: categories/日记/index.html
INFO  Generated: guides/oos.html
INFO  Generated: tags/常见问题/index.html
INFO  Generated: categories/常见问题/index.html
INFO  Generated: categories/角色攻略/index.html
INFO  Generated: tags/报名相关/index.html
INFO  Generated: tags/开黑啦/index.html
INFO  Generated: tags/smash-gg/index.html
INFO  Generated: guides/index.html
INFO  Generated: tags/体术角色/index.html
INFO  Generated: 404.html
INFO  Generated: tags/道具角色/index.html
INFO  Generated: index.html
INFO  Generated: diary/first/index.html
INFO  Generated: archives/2020/10/index.html
INFO  Generated: faq/register/index.html
INFO  Generated: archives/2020/08/index.html
INFO  Generated: js/aplayer.js
INFO  Generated: archives/2020/index.html
INFO  Generated: guide/char/rob/index.html
INFO  Generated: js/issues.js
INFO  Generated: js/app.js
INFO  Generated: js/search.js
INFO  Generated: css/style.css
INFO  Generated: js/valine.js
INFO  28 files generated in 766 ms
INFO  Deploying: cos
INFO  Uploading files to COS...
INFO  Deploy done: cos
INFO  Upload: 404.html
INFO  Upload: archives\2020\08\index.html
INFO  Upload: archives\index.html
INFO  Upload: archives\2020\10\index.html
INFO  Upload: archives\2020\index.html
INFO  Upload: categories\index.html
INFO  Upload: categories\常见问题\index.html
INFO  Upload: categories\日记\index.html
INFO  Upload: categories\角色攻略\index.html
INFO  Upload: diary\first\index.html
INFO  Upload: faq\register\index.html
INFO  Upload: guide\char\rob\index.html
INFO  Upload: guides\index.html
INFO  Upload: guides\oos.html
INFO  Upload: index.html
INFO  Upload: js\aplayer.js
INFO  Upload: js\app.js
INFO  Upload: js\issues.js
INFO  Upload: js\search.js
INFO  Upload: tags\index.html
INFO  Upload: tags\smash-gg\index.html
INFO  Upload: tags\体术角色\index.html
INFO  Upload: tags\常见问题\index.html
INFO  Upload: tags\开黑啦\index.html
INFO  Upload: tags\道具角色\index.html
INFO  Upload: tags\报名相关\index.html
INFO  Upload: css\style.css
INFO  Upload: js\valine.js
(node:7584) UnhandledPromiseRejectionWarning: #<Object>
(node:7584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
INFO  Good bye

**Comment by sdlzhd** [comment]
谢谢你的反馈，我将在近期查看该问题

**Comment by sdlzhd** [comment]
未能复现该问题

**Comment by fi6** [comment]
> 未能复现该问题

应该是海外IP导致的
